# Generated by Django 5.2.3 on 2025-06-19 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_especialidade', models.CharField(max_length=100)),
                ('anos_experiencia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_exame', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_medicamento', models.CharField(max_length=100)),
                ('validade', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_medico', models.CharField(max_length=120)),
                ('data_nascimento', models.DateField()),
                ('cpf_medico', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_paciente', models.CharField(max_length=11)),
                ('nome_paciente', models.CharField(max_length=120)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_consulta', models.DateTimeField()),
                ('motivo_consulta', models.CharField(max_length=120)),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinica_medica.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica_medica.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescricao', models.CharField(max_length=100)),
                ('data_emissao', models.DateField()),
                ('validade', models.DateField()),
                ('medicamentos', models.ManyToManyField(to='clinica_medica.medicamento')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica_medica.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica_medica.paciente')),
            ],
        ),
    ]
